/* Static authoring and result inspection; no network requests or execution. */
(() => {
'use strict';
const D=window.VT_DATA,$=s=>document.querySelector(s),E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={completed:'完成',passed:'通过',failed:'失败',partial:'部分结果',insufficient_evidence:'证据不足',findings:'发现候选',pending:'待执行',running:'执行中',remote_running:'远端仍运行',skipped:'已跳过',interrupted:'已中断',cancelled:'已取消',ok:'已评分'};
const badge=s=>`<span class="pill ${E(s)}">${E(labels[s]||s)}</span>`;
const pretty=v=>JSON.stringify(v,null,2),clone=v=>JSON.parse(JSON.stringify(v));
function notice(s){$('#notice').textContent=s;}
function download(value,name,type='application/json'){const a=document.createElement('a');const u=URL.createObjectURL(new Blob([typeof value==='string'?value:pretty(value)],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function modal(html){$('#modal-body').innerHTML=html;$('#modal').showModal();}
function nav(items){$('#navigation').innerHTML=items.map(([id,text])=>`<button data-page="${id}" class="${page===id?'selected':''}">${text}</button>`).join('');}
function field(name,label,value,type='text',extra=''){return `<div class="field"><label for="${E(name)}">${E(label)}</label><input id="${E(name)}" data-meta="${E(name)}" type="${type}" value="${E(value)}" ${extra}></div>`;}
function source(input,path){return {input,...(path?{path}:{} )};}
let audioContext=null;
let page=D.mode==='author'?'task':'overview',selected=0,tab='summary',filter='',statusFilter='',offset=0,task,history=[],notes={},qaLabels={};
const templates={
 audio:{title:'录音分析',subtitle:'逐轨体检与应答候选，保留人工复核入口',inputs:{audio:'assets/call.wav'},steps:[{id:'health',tool:'audio',action:'inspect',params:{inputs:[source('audio')]}},{id:'qa',tool:'qa',action:'analyze',params:{inputs:[source('audio')],include_audio:true}}]},
 sip:{title:'功能拨测',subtitle:'批量用例、接收录音和结构化断言',inputs:{queue:'cases/queue.json'},steps:[{id:'calls',tool:'sip',action:'batch',environment:'lab',params:{queue:source('queue')}}]},
 load:{title:'SIPp 压力测试',subtitle:'独立压力包、CPS 与在途并发',inputs:{package:'sipp-package'},steps:[{id:'load',tool:'sip',action:'sipp-load',environment:'lab',params:{package:source('package')}}]},
 capture:{title:'抓包排障',subtitle:'远端采集、索引和 RTP/RTCP 报告',inputs:{inventory:'capture/hosts.json'},steps:[{id:'capture',tool:'capture',action:'batch',environment:'lab',params:{inventory:source('inventory'),seconds:60}},{id:'sessions',tool:'sessions',action:'index',params:{batch:[{step:'capture',path:'data/batch.json'}]}},{id:'report',tool:'report',action:'build',params:{pcap:[{step:'capture',path:'data/**/*.pcap*'}],decode_rtp:true}}]},
 quality:{title:'听感评分',subtitle:'NISQA 无参考五维评分，双轨分别处理',inputs:{audio:'assets/call.wav'},steps:[{id:'nisqa',tool:'nisqa',action:'analyze',params:{inputs:[source('audio')],channel:'both'}}]},
 compare:{title:'有参考音质比较',subtitle:'ViSQOL 比较同一句原声和实际接收音频',inputs:{reference:'assets/reference.wav',degraded:'assets/rx.wav'},steps:[{id:'visqol',tool:'visqol',action:'score',params:{reference:source('reference'),degraded:source('degraded')}}]},
 golden:{title:'黄金集评估',subtitle:'使用已有人工标签；不自动生成复核结论',inputs:{golden:'qa/golden.json',results:'qa/results.jsonl'},steps:[{id:'evaluate',tool:'qa',action:'evaluate',params:{golden:source('golden'),results:source('results')}}]}
};
function makeTask(key){return {schema_version:'1.0',id:'task-'+Date.now().toString(36),...clone(templates[key])};}
function cleanupTask(t){const {subtitle,...rest}=t;return rest;}
function validateTask(t){if(!t||t.schema_version!=='1.0'||!Array.isArray(t.steps)||!t.inputs||typeof t.inputs!=='object'||!t.title||!/^[A-Za-z][\w-]{0,63}$/.test(t.id))throw Error('任务格式、标题或 ID 无效');if(t.steps.length<1||t.steps.length>100)throw Error('任务须包含 1–100 个步骤');for(const p of Object.values(t.inputs))if(typeof p!=='string'||!p||p.startsWith('/')||p.split('/').includes('..'))throw Error('素材须为根目录内的相对路径');const ids=new Set();for(const s of t.steps){if(!/^[A-Za-z][\w-]{0,63}$/.test(s.id)||ids.has(s.id))throw Error('步骤 ID 无效或重复');if(!D.catalog[`${s.tool}.${s.action}`])throw Error('不支持的工具步骤');if(!s.params||typeof s.params!=='object'||Array.isArray(s.params))throw Error('参数必须是对象');const names=new Set(D.catalog[`${s.tool}.${s.action}`].arguments.map(a=>a.name));for(const k of Object.keys(s.params))if(!names.has(k))throw Error('未知参数 '+k);const refs=v=>{if(Array.isArray(v))v.forEach(refs);else if(v&&typeof v==='object'){if(v.step&&!ids.has(v.step))throw Error('文件只能引用前序步骤：'+v.step);if(v.input&&!Object.hasOwn(t.inputs,v.input))throw Error('未声明的输入：'+v.input);Object.values(v).forEach(refs);}};refs(s.params);for(const d of s.depends_on||[])if(!ids.has(d))throw Error('依赖只能引用前序步骤');ids.add(s.id);}return t;}
function persist(){try{validateTask(task);localStorage.setItem('voice-tools.task.v1',pretty(task));}catch(e){notice('未保存草稿：'+e.message+'。仍可查看和修正。');}}
function change(fn){const before=clone(task),beforeSelected=selected;try{fn();validateTask(task);}catch(e){task=before;selected=beforeSelected;throw e;}history.push(before);if(history.length>30)history.shift();persist();render();}
function author(){nav([['task','▤ 任务编排'],['inputs','≋ 输入素材'],['environments','⌘ 执行环境'],['delivery','↗ 打包与交付']]);$('#heading').textContent={task:'任务编排',inputs:'输入素材',environments:'执行环境',delivery:'打包与交付'}[page];$('#actions').innerHTML='<button data-act="templates">选择模板</button><button data-act="import">导入任务</button><button data-act="export" class="primary">导出任务说明</button>';let html='';
 if(page==='task')html=`<section class="panel"><div class="form-grid">${field('title','任务名称',task.title)}${field('id','任务 ID',task.id)}</div></section><div class="editor-grid"><section class="panel"><div class="split-title"><h2>顺序步骤 <span class="pill">${task.steps.length}</span></h2><button data-act="undo" ${history.length?'':'disabled'}>撤销</button></div><p class="help">按顺序启动。批量并发使用 SIP 队列；前序输出可作为后续输入。</p>${task.steps.map((s,i)=>`<article tabindex="0" role="button" aria-label="选择步骤 ${i+1} ${E(s.id)}" data-step="${i}" aria-pressed="${selected===i}" class="step ${selected===i?'selected':''}"><span class="number">${i+1}</span><div class="step-copy"><b>${E(s.title||s.id)}</b><p>${E(s.tool)} · ${E(s.action)}</p></div><div class="step-controls"><button data-act="up" data-index="${i}" aria-label="上移步骤 ${i+1}" ${i?'':'disabled'}>↑</button><button data-act="down" data-index="${i}" aria-label="下移步骤 ${i+1}" ${i<task.steps.length-1?'':'disabled'}>↓</button></div></article>`).join('')}<div class="step-add"><select id="add-command" aria-label="新增工具步骤">${Object.keys(D.catalog).map(k=>`<option>${E(k)}</option>`).join('')}</select><button data-act="add">添加</button></div></section><section class="panel">${parameterPanel()}</section></div>`;
 if(page==='inputs')html=`<section class="panel"><h2>输入清单</h2><p class="help">路径相对于打包根目录。打包器自动收集用例引用的 WAV、media.json、事件和 ViSQOL 配对素材。</p><div class="form-grid">${Object.entries(task.inputs).map(([k,v])=>`<div class="field"><label>${E(k)}</label><input data-input="${E(k)}" value="${E(v)}"></div>`).join('')}</div><button style="margin-top:18px" data-act="add-input">添加输入</button><details><summary>检查本地文件清单</summary><p class="help">选择素材根目录，只核对名称；不上传或自动复制文件。CLI 会再次核对全部引用和摘要。</p><input id="folder" type="file" webkitdirectory multiple><div id="input-check"></div></details></section><section class="panel"><h2>已有 SIP 断言</h2><p>在 SIP 用例工作台中配置应答码、接收 RTP、有效音频、DTMF 与音调；任务打包会保留这些字段。</p><p class="help">素材角色来自实际录制配置。接收 RX 与本地发送源不能冒充同步双轨录音。</p></section>`;
 if(page==='environments')html=`<section class="panel"><h2>环境留在执行机</h2><p>任务只引用环境名称。SIP 地址、端口、SSH/HOMER 配置和模型路径由执行端提供；密码使用执行端环境变量。</p><table><thead><tr><th>步骤</th><th>环境</th><th>网络要求</th></tr></thead><tbody>${task.steps.map(s=>`<tr><td>${E(s.id)}</td><td>${E(s.environment||'默认／无')}</td><td>${['sip','capture','homer'].includes(s.tool)?'按操作需要业务网络':'离线分析或显式查询'}</td></tr>`).join('')}</tbody></table><div class="warning">Mac Docker 的原始包回放交给 Linux。普通 SIP 网络需 Docker Desktop 4.34+ 并启用 host networking；离线分析不受此限制。</div><button data-act="profile">下载执行机配置模板</button></section>`;
 if(page==='delivery')html=`<section class="panel"><h2>一次准备，每次只传任务和结果</h2><ol class="checklist"><li>导出 task.json，将素材放入所声明的相对路径。</li><li>本机打包，校验素材与版本。任务包不包含模型或凭据。</li><li>把 .vtask.zip 复制到执行机，检查环境后运行。</li><li>收集 .vresult.zip，带回本机生成离线复查页。</li></ol><pre>./vt task pack task.json --root ./workspace --out task.vtask.zip
./vt task check task.vtask.zip --profile executor.json
./vt task run task.vtask.zip --profile executor.json
./vt task status RUN_ID
./vt task collect RUN_ID --out result.vresult.zip
./vt task review result.vresult.zip --out ./review</pre><p class="help">run 在独立容器中执行，断开终端不会取消任务。check 不拨号、不连接 SSH/HOMER。</p></section><section class="panel"><h2>任务说明预览</h2><pre>${E(pretty(task))}</pre></section>`;
 $('#workspace').innerHTML=html;
}
function parameterPanel(){const s=task.steps[selected];if(!s)return '<div class="empty">添加一个工具步骤开始编排。</div>';const spec=D.catalog[`${s.tool}.${s.action}`];return `<div class="split-title"><h2>${E(s.tool)} · ${E(s.action)}</h2><button data-act="remove" ${task.steps.length<=1?'disabled':''}>删除</button></div><div class="form-grid">${field('step-id','步骤 ID',s.id)}${field('step-env','执行环境（可空）',s.environment||'')}${field('step-timeout','执行时限（秒）',s.timeout_s||3600,'number')}</div><div class="info">${spec.output_kind==='file'?'此步骤生成一个文件：output.json':'此步骤产物位于 data/ 目录'}。输出目录由执行器管理。</div>${spec.arguments.filter(a=>!['output','runtime'].includes(a.role)).map(a=>paramField(a,s)).join('')}<details><summary>完整参数 JSON</summary><textarea id="params-json" aria-label="完整参数 JSON">${E(pretty(s.params))}</textarea><button data-act="apply-json">应用参数</button><p class="help">文件引用格式：{"input":"audio"} 或 {"step":"前序步骤","path":"data/rx.wav"}。多输入使用数组。</p></details>`;}
function paramField(a,s){const value=s.params[a.name];const label=a.name+(a.required?' *':'');if(a.type==='boolean')return `<label><input type="checkbox" id="param-${E(a.name)}" data-param="${E(a.name)}" ${value?'checked':''}> ${E(label)}</label><p class="help">${E(a.help||'')}</p>`;const complex=['input','input_group'].includes(a.role)||a.repeatable||a.nargs==='+'||a.nargs==='*'||typeof a.nargs==='number'&&a.nargs>0;let input;if(complex)input=`<textarea id="param-${E(a.name)}" data-param="${E(a.name)}" data-kind="json" rows="2" style="min-height:65px" placeholder="${E(a.role==='input'?'使用 input/step 引用':'JSON 数组')}">${value===undefined?'':E(pretty(value))}</textarea>`;else if(a.choices)input=`<select id="param-${E(a.name)}" data-param="${E(a.name)}"><option value="">使用默认值</option>${a.choices.map(v=>`<option value="${E(v)}" ${String(value)===String(v)?'selected':''}>${E(v)}</option>`).join('')}</select>`;else input=`<input id="param-${E(a.name)}" data-param="${E(a.name)}" type="${['int','float'].includes(a.type)?'number':'text'}" value="${E(value??'')}" placeholder="${E(a.default??'')}" ${a.type==='float'?'step="any"':''}>`;return `<div class="field"><label for="param-${E(a.name)}">${E(label)}</label>${input}<p class="help">${E(a.help||'')}</p></div>`;}
function allAudio(){return D.steps.flatMap(s=>s.audio||[]).concat(D.inputs_audio||[]);}
function audioView(item){if(!item.audio?.length)return '<div class="empty">此步骤没有接收录音。可在证据文件中核对输入或前序步骤。</div>';return `<select id="audio-select" aria-label="选择录音">${item.audio.map((a,i)=>`<option value="${i}">${E(a.name)}</option>`).join('')}</select><div id="audio-body"></div>`;}
function routeChannel(value){ const p=$('#audio');if(!audioContext){audioContext=new AudioContext();const source=audioContext.createMediaElementSource(p),split=audioContext.createChannelSplitter(2),merge=audioContext.createChannelMerger(2),left=audioContext.createGain(),right=audioContext.createGain();source.connect(split);split.connect(left,0);split.connect(right,1);left.connect(merge,0,0);right.connect(merge,0,1);merge.connect(audioContext.destination);audioContext.gains=[left,right];}audioContext.gains[0].gain.value=value==='right'?0:1;audioContext.gains[1].gain.value=value==='left'?0:1;audioContext.resume();}
function stopAudio(){for(const p of document.querySelectorAll('audio')){p.ontimeupdate=null;p.pause();}}
function drawAudio(a){if(!a)return;stopAudio();if(audioContext){audioContext.close();audioContext=null;}$('#audio-body').innerHTML=`<p class="help">${E(a.name)} · ${a.wave?`${a.wave.channels.length} 声道 · ${a.wave.duration.toFixed(2)} 秒`:'使用原始文件试听'}</p><svg class="wave" id="wave" viewBox="0 0 800 150" role="img" aria-label="录音波形"></svg>${a.wave?.channels.length===2?'<label>试听声道 <select id="audio-channel"><option value="both">双声道</option><option value="left">仅左声道</option><option value="right">仅右声道</option></select></label>':''}<audio id="audio" controls preload="metadata" src="${E(a.path)}"></audio><div class="toolbar"><label>片段起点 <input id="loop-start" type="number" min="0" step="0.1" value="0" style="width:85px"></label><label>片段终点 <input id="loop-end" type="number" min="0" step="0.1" value="${a.wave?Math.min(10,a.wave.duration):10}" style="width:85px"></label><button data-act="play-segment">试听片段</button><label><input id="loop" type="checkbox"> 循环</label></div>`;if(a.wave){const channels=a.wave.channels,h=150/channels.length;$('#wave').innerHTML=channels.map((bins,c)=>bins.map((v,i)=>`<rect x="${i*800/bins.length}" y="${c*h+h/2-v*(h-12)/2}" width="${Math.max(.5,800/bins.length)}" height="${Math.max(.5,v*(h-12))}"/>`).join('')).join('')+'<line class="playhead" id="playhead" x1="0" x2="0" y1="0" y2="150"/>';$('#wave').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();$('#audio').currentTime=(e.clientX-r.left)/r.width*a.wave.duration;};}$('#audio').ontimeupdate=()=>{const p=$('#audio'),end=Number($('#loop-end').value);if($('#playhead')&&p.duration){const x=p.currentTime/p.duration*800;$('#playhead').setAttribute('x1',x);$('#playhead').setAttribute('x2',x);}if(p.dataset.segment==='yes'&&p.currentTime>=end){if($('#loop').checked)p.currentTime=Number($('#loop-start').value);else{p.pause();p.dataset.segment='no';}}};}
const reviewFields=['sample_id','audio_sha256','opportunity_id','at_s','observed_until_s','status','decision','reviewer','reviewed_at','notes'];
function saveQa(el){const r=qaRows(D.steps[selected])[+el.dataset.row],key=r.sample_id+':'+r.opportunity_id;qaLabels[key]={...(qaLabels[key]||{}),[el.dataset.qa]:el.value,reviewed_at:new Date().toISOString()};}
function qaRows(s){return s.records.filter(r=>r.sample_id&&r.audio_sha256&&Array.isArray(r.result?.opportunities)).flatMap(r=>r.result.opportunities.map(o=>({sample_id:r.sample_id,audio_sha256:r.audio_sha256,opportunity_id:o.id,at_s:o.at_s,observed_until_s:o.observed_until_s,status:o.status,input:r.input,playback:r.playback})));}
function qaView(s){const rows=qaRows(s);return `<section class="panel"><h2>人工质检标注</h2><p class="help">先试听并核对时间窗，再填写结论。导出的 CSV 可交给 qa promote；未填写的项目仍是未复核。</p><button data-act="export-labels">导出本步骤人工标签 CSV</button>${rows.slice(offset,offset+30).map((r,i)=>{const key=r.sample_id+':'+r.opportunity_id,v=qaLabels[key]||{};return `<article class="panel"><b>${E(r.input?.split('/').pop())} · ${E(r.opportunity_id)}</b><p>${r.at_s}–${r.observed_until_s} s · 候选 ${E(r.status)}</p>${r.playback?`<button data-qa-audio="${offset+i}">试听这个时间窗</button>`:''}<label>人工结论 <select data-qa="decision" data-row="${offset+i}">${[['','未复核'],['audible','有可听应答'],['missing','缺少应答'],['delayed','应答延迟'],['exclude','排除'],['uncertain','无法确认']].map(([k,n])=>`<option value="${k}" ${v.decision===k?'selected':''}>${n}</option>`).join('')}</select></label><label>复核人 <input data-qa="reviewer" data-row="${offset+i}" value="${E(v.reviewer||'')}"></label><label>依据／备注 <input data-qa="notes" data-row="${offset+i}" value="${E(v.notes||'')}"></label></article>`;}).join('')||'<div class="empty">此步骤没有可标注的应答机会。</div>'}<div class="pager"><button data-act="prev" ${offset?'':'disabled'}>上一页</button><button data-act="next" ${offset+30<rows.length?'':'disabled'}>下一页</button></div></section>`;}
function overview(){const r=D.receipt;const counts=s=>r.steps.filter(x=>s.includes(x.status)).length;return `<div class="stats"><div class="stat"><strong>${r.steps.length}</strong><span>步骤总数</span></div><div class="stat"><strong>${counts(['completed','findings'])}</strong><span>执行完成</span></div><div class="stat"><strong>${counts(['failed','interrupted','skipped'])}</strong><span>失败／中断／跳过</span></div><div class="stat"><strong>${counts(['partial','insufficient_evidence','remote_running'])}</strong><span>部分或证据不足</span></div></div><section class="panel"><div class="split-title"><h2>${E(r.title)}</h2>${badge(r.status)}</div><p class="help">${E(r.run_id)} · voice_tools ${E(r.tool_version)} · ${E(r.environment.machine||'')}</p><div class="toolbar"><input id="search" placeholder="搜索步骤、工具或状态" value="${E(filter)}" aria-label="搜索结果"><select id="status-filter" aria-label="筛选状态"><option value="">全部状态</option>${[...new Set(r.steps.map(s=>s.status))].map(s=>`<option value="${E(s)}" ${statusFilter===s?'selected':''}>${E(labels[s]||s)}</option>`).join('')}</select></div><table><thead><tr><th>步骤</th><th>工具</th><th>结果</th><th>证据</th></tr></thead><tbody>${D.steps.map((s,i)=>({...s,i})).filter(s=>(!filter||pretty(s).toLowerCase().includes(filter.toLowerCase()))&&(!statusFilter||s.status===statusFilter)).map(s=>`<tr><td><button class="row-button" data-open="${s.i}">${E(s.id)} ↗</button></td><td>${E(s.tool)} ${E(s.action)}</td><td>${badge(s.status)}</td><td>${s.files.length} 文件 · ${s.audio.length} 录音</td></tr>`).join('')}</tbody></table><p class="help">断言通过不等于业务语义正确。${D.manifest.files} 个包内文件已通过摘要校验。</p></section>`;}
function detail(){const s=D.steps[selected];if(!s)return '<div class="empty">没有步骤结果。</div>';let body='';if(tab==='summary')body=`<div class="grid"><section class="panel"><h2>执行与证据</h2><p>${badge(s.status)} ${s.exit_code!==undefined?'退出码 '+s.exit_code:''}</p>${s.reason?`<div class="warning">${E(s.reason)}</div>`:''}<p class="help">开始 ${E(s.started_at||'未启动')}<br>结束 ${E(s.finished_at||'未知')}</p><h3>结构化断言</h3>${s.assertions.length?s.assertions.map(a=>`<div class="assertion"><b>${E(a.id||a.type)} · ${E(a.type)}</b>${badge(a.status)}<pre>${E(pretty({expected:a.expected,actual:a.actual,reason:a.reason}))}</pre></div>`).join(''):'<p class="help">没有结构化断言产物；不能解释为全部通过。</p>'}</section><section class="panel"><h2>步骤事件</h2><div class="timeline">${s.records.slice(0,35).map(r=>`<div class="event"><small>${E(r.at_s??r.time_s??r.elapsed_s??r.timestamp??'')}</small><p>${E(r.event||r.type||r.status||'分析记录')}</p></div>`).join('')||'<p class="help">此步骤没有事件记录。</p>'}</div>${s.records_truncated?'<p class="help">预览已截断，完整 JSONL 保留在证据文件中。</p>':''}</section></div>`;
 if(tab==='audio')body=`<section class="panel"><h2>录音与片段</h2>${audioView(s)}</section><section class="panel"><h2>人工复核笔记</h2><textarea id="review-note" placeholder="记录听到的现象、时间范围和依据；不改写原始证据。">${E(notes[s.id]||'')}</textarea><div class="actions"><button data-act="save-note">保存到本次复查</button><button data-act="export-notes">导出标注</button></div></section>`;
 if(tab==='scores')body=`<section class="panel"><h2>音质与分析记录</h2><p class="help">NISQA 是模型预测，ViSQOL 是有参考比较；不能混为人工 MOS。点击已有时间范围可定位到唯一对应的录音。</p>${s.scores.length?s.scores.slice(offset,offset+50).map((r,i)=>`<div class="panel"><button class="row-button" data-score="${offset+i}">${E(String(r.file||r.degraded||r.input||'评分记录').split('/').pop())} · ${E(r.channel||'')} ${r.start_seconds!==undefined?`${Number(r.start_seconds).toFixed(1)}–${Number(r.end_seconds).toFixed(1)} s`:''}</button>${badge(r.status||'ok')}<div class="score-grid">${Object.entries(r.scores||{moslqo:r.moslqo}).filter(([,v])=>v!==undefined).map(([k,v])=>`<div><small>${E(k)}</small><b>${typeof v==='number'?v.toFixed(2):'—'}</b><div class="score-bar"><span style="width:${typeof v==='number'?Math.max(0,Math.min(100,v/5*100)):0}%"></span></div></div>`).join('')}</div>${r.reason?`<p class="help">${E(r.reason)}</p>`:''}</div>`).join(''):'<div class="empty">此步骤没有音质预测记录。其余统计保存在结构化详情。</div>'}<div class="pager"><button data-act="prev" ${offset?'':'disabled'}>上一页</button><span>每页 50 项</span><button data-act="next" ${offset+50<s.scores.length?'':'disabled'}>下一页</button></div>${(s.details||[]).map(d=>`<details><summary>${E(d.name)}</summary><pre>${E(pretty(d.value))}</pre></details>`).join('')}</section>`;
 if(tab==='qa')body=s.gaps_review?`<section class="panel"><h2>输出间隙标注</h2><p>此页面由当前安装版本从数据重建。<a href="${E(s.gaps_review)}" target="_blank" rel="noopener">单独打开完整时间轴</a></p><iframe title="输出间隙时间轴与人工标注" src="${E(s.gaps_review)}" style="width:100%;height:1000px;border:0"></iframe></section>`:qaView(s);
 if(tab==='evidence')body=`<section class="panel"><h2>质检与协议证据</h2><p class="help">保留采集点、候选问题和原始字段。候选现象需要结合录音与抓包复核。</p>${s.records.length?s.records.slice(offset,offset+50).map((r,i)=>`<details><summary>${E(r.sample_id||r.event||r.type||r.status||'记录 '+(offset+i+1))} ${E(r.input||r.file||'')}</summary><pre>${E(pretty(r))}</pre></details>`).join(''):'<div class="empty">没有逐条记录；请检查下方结构化报告或证据文件。</div>'}<div class="pager"><button data-act="prev" ${offset?'':'disabled'}>上一页</button><button data-act="next" ${offset+50<s.records.length?'':'disabled'}>下一页</button></div>${(s.details||[]).map(d=>`<details open><summary>${E(d.name)}</summary><pre>${E(pretty(d.value))}</pre></details>`).join('')}</section>`;
 if(tab==='files')body=`<section class="panel"><h2>原始证据文件</h2><p class="help">保留原始结构。HTML／脚本只提供下载，不自动执行包内页面。</p><table class="files"><thead><tr><th>文件</th><th>大小</th></tr></thead><tbody>${s.files.slice(offset,offset+50).map(f=>`<tr><td><a href="${E(f.path)}" download>${E(f.name)}</a></td><td>${(f.bytes/1024).toFixed(1)} KiB</td></tr>`).join('')}</tbody></table><div class="pager"><button data-act="prev" ${offset?'':'disabled'}>上一页</button><span>${offset+1}–${Math.min(offset+50,s.files.length)} / ${s.files.length}</span><button data-act="next" ${offset+50<s.files.length?'':'disabled'}>下一页</button></div></section>`;
 return `<div class="toolbar"><button data-page="overview">← 批次总览</button><select id="step-select" aria-label="选择步骤">${D.steps.map((x,i)=>`<option value="${i}" ${i===selected?'selected':''}>${E(x.id)} · ${E(x.tool)}</option>`).join('')}</select></div><div class="tabs">${[['summary','执行与断言'],['audio','录音复查'],['scores','评分与统计'],['qa','人工标签'],['evidence','质检与协议'],['files','证据文件']].map(([k,l])=>`<button data-tab="${k}" class="${tab===k?'selected':''}">${l}</button>`).join('')}</div>${body}`;
}
function result(){nav([['overview','▦ 批次总览'],['detail','≋ 证据复查'],['provenance','⌘ 执行来源']]);$('#heading').textContent=page==='overview'?'结果复查':page==='detail'?'单步证据':'执行来源';$('#subtitle').textContent='从执行结果追溯到参数、录音和原始产物。';$('#eyebrow').textContent='OFFLINE EVIDENCE REVIEW';$('#actions').innerHTML='<button data-act="export-notes">导出复核笔记</button>';$('#workspace').innerHTML=page==='overview'?overview():page==='detail'?detail():`<section class="panel"><h2>运行与环境</h2><pre>${E(pretty(D.receipt))}</pre><p class="help">这是已结束运行的离线回执。模型分数、采集缺口和接收录音不自动确定故障责任。</p></section>`;if(page==='detail'&&tab==='audio')drawAudio(D.steps[selected].audio[0]);}
function render(){stopAudio();if(audioContext){audioContext.close();audioContext=null;}if(D.mode==='author')author();else result();}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-step]');if(!b)return;try{
 if(b.dataset.page){page=b.dataset.page;render();return;}
 if(b.dataset.tab){tab=b.dataset.tab;offset=0;render();return;}
 if(b.dataset.open!==undefined){selected=+b.dataset.open;page='detail';tab='summary';offset=0;render();return;}
 if(b.dataset.step!==undefined&&!e.target.closest('button')){selected=+b.dataset.step;render();return;}
 if(b.dataset.template){task=cleanupTask(makeTask(b.dataset.template));selected=0;history=[];persist();$('#modal').close();render();return;}
 if(b.dataset.qaAudio!==undefined){const r=qaRows(D.steps[selected])[+b.dataset.qaAudio],a=allAudio().find(a=>a.path===r.playback);if(!a)throw Error('没有对应录音');modal('<h2>质检时间窗试听</h2><div id="audio-body"></div>');drawAudio(a);$('#loop-start').value=r.at_s;$('#loop-end').value=r.observed_until_s;return;}
 if(b.dataset.score!==undefined){const r=D.steps[selected].scores[+b.dataset.score];const matches=[...new Map(allAudio().filter(a=>a.path===r.playback).map(a=>[a.path,a])).values()];if(matches.length!==1){notice('未找到唯一对应录音；请到原步骤选择文件复查，未自动猜测时间对齐。');return;}modal('<h2>评分片段试听</h2><div id="audio-body"></div>');drawAudio(matches[0]);$('#loop-start').value=r.start_seconds||0;$('#loop-end').value=r.end_seconds||10;if($('#audio-channel')&&['left','right'].includes(r.channel)){$('#audio-channel').value=r.channel;routeChannel(r.channel);}return;}
 const a=b.dataset.act;if(a==='templates')modal('<h2>选择一个起点</h2><div class="templates">'+Object.entries(templates).map(([k,v])=>`<button class="template" data-template="${k}"><b>${v.title}</b><small>${v.subtitle}</small></button>`).join('')+'</div>');
 else if(a==='export'){validateTask(task);download(task,'task.json');notice('已导出任务说明；还需用 task pack 收集素材并核对完整参数。');}
 else if(a==='import')$('#import-file').click();
 else if(a==='undo'&&history.length){task=history.pop();selected=Math.min(selected,task.steps.length-1);persist();render();}
 else if(a==='add'){const [tool,action]=$('#add-command').value.split('.');change(()=>{task.steps.push({id:'step-'+Date.now().toString(36),tool,action,params:{}});selected=task.steps.length-1;});}
 else if(a==='remove')change(()=>{task.steps.splice(selected,1);selected=Math.max(0,selected-1);});
 else if(a==='up'||a==='down'){const i=+b.dataset.index,j=i+(a==='up'?-1:1);change(()=>{[task.steps[i],task.steps[j]]=[task.steps[j],task.steps[i]];selected=j;});}
 else if(a==='apply-json'){const params=JSON.parse($('#params-json').value);change(()=>{task.steps[selected].params=params;});}
 else if(a==='add-input')modal('<h2>添加输入</h2><label>名称</label><input id="input-name" value="audio2"><label>相对路径</label><input id="input-path" value="assets/another.wav"><button data-act="confirm-input">添加</button>');
 else if(a==='confirm-input'){const name=$('#input-name').value,path=$('#input-path').value;if(!/^[A-Za-z][\w-]*$/.test(name)||!path||path.startsWith('/')||path.split('/').includes('..'))throw Error('名称或相对路径无效');change(()=>{task.inputs[name]=path;});$('#modal').close();}
 else if(a==='profile')download({schema_version:'1.0',network_allowed:false,model_dir:'/models/nisqa',visqol_dir:'/opt/visqol/source',secret_env:[],environments:{lab:{params:{},sip:{target_uri:'sip:1001@192.0.2.10',network:{public_address:'192.0.2.20'}}}}},'executor.example.json');
 else if(a==='export-labels'){document.querySelectorAll('[data-qa]').forEach(el=>saveQa(el));const rows=qaRows(D.steps[selected]).map(r=>({...r,...qaLabels[r.sample_id+':'+r.opportunity_id]})).filter(r=>r.decision);if(!rows.length)throw Error('没有已复核标签');if(rows.some(r=>!r.reviewer?.trim()))throw Error('已复核标签需要填写复核人');const cell=v=>{let text=String(v??'');if(/^[=+@-]/.test(text.trimStart()))text="'"+text;return '"'+text.replaceAll('"','""')+'"';};download('﻿'+[reviewFields,...rows.map(r=>reviewFields.map(k=>r[k]))].map(row=>row.map(cell).join(',')).join('\r\n'),'review.csv','text/csv;charset=utf-8');notice('已导出 '+rows.length+' 项人工标签；原始证据未修改。');}
 else if(a==='save-note'){notes[D.steps[selected].id]=$('#review-note').value;notice('笔记已保留在本次页面会话，请导出后再关闭。');}
 else if(a==='export-notes')download({schema_version:'1.0',run_id:D.receipt?.run_id,reviewed_at:new Date().toISOString(),notes},'review-notes.json');
 else if(a==='prev'||a==='next'){const size=tab==='qa'?30:50;offset=Math.max(0,offset+(a==='next'?size:-size));render();}
 else if(a==='play-segment'){const p=$('#audio'),start=Number($('#loop-start').value),end=Number($('#loop-end').value);if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||end<=start||Number.isFinite(p.duration)&&end>p.duration+.05)throw Error('试听范围无效');p.currentTime=start;p.dataset.segment='yes';p.play().catch(x=>notice('播放未开始：'+x.message));}
}catch(error){notice(error.message);}});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-step]')){e.preventDefault();selected=+e.target.dataset.step;render();document.querySelector('[data-step="'+selected+'"]')?.focus();}});
document.addEventListener('change',e=>{const el=e.target;try{if(el.dataset.meta){const key=el.dataset.meta;if(key==='title'||key==='id')task[key]=el.value;else if(key==='step-id')task.steps[selected].id=el.value;else if(key==='step-env'){if(el.value)task.steps[selected].environment=el.value;else delete task.steps[selected].environment;}else if(key==='step-timeout')task.steps[selected].timeout_s=Number(el.value);persist();}
 else if(el.dataset.input){task.inputs[el.dataset.input]=el.value;persist();}
 else if(el.dataset.param){const key=el.dataset.param,a=D.catalog[`${task.steps[selected].tool}.${task.steps[selected].action}`].arguments.find(x=>x.name===key);if(el.type==='checkbox')task.steps[selected].params[key]=el.checked;else if(el.value==='')delete task.steps[selected].params[key];else task.steps[selected].params[key]=el.dataset.kind==='json'?JSON.parse(el.value):['int','float'].includes(a.type)?Number(el.value):el.value;persist();}
 else if(el.dataset.qa){const r=qaRows(D.steps[selected])[+el.dataset.row],key=r.sample_id+':'+r.opportunity_id;qaLabels[key]={...(qaLabels[key]||{}),[el.dataset.qa]:el.value,reviewed_at:new Date().toISOString()};}
 else if(el.id==='step-select'){selected=+el.value;offset=0;render();}
 else if(el.id==='audio-channel'){
 routeChannel(el.value);
 }
 else if(el.id==='audio-select')drawAudio(D.steps[selected].audio[+el.value]);
 else if(el.id==='status-filter'){statusFilter=el.value;render();}
 else if(el.id==='folder'){const files=new Set([...el.files].map(f=>f.webkitRelativePath.split('/').slice(1).join('/')));$('#input-check').innerHTML='<ul class="checklist">'+Object.entries(task.inputs).map(([k,p])=>`<li>${E(k)}：${files.has(p)||[...files].some(f=>f.startsWith(p+'/'))?'已找到':'未找到'} · ${E(p)}</li>`).join('')+'</ul>';}
}catch(error){notice(error.message);}});
document.addEventListener('input',e=>{if(e.target.dataset.qa)saveQa(e.target);if(e.target.id==='search'){filter=e.target.value;const pos=e.target.selectionStart;render();$('#search').focus();$('#search').setSelectionRange(pos,pos);}});
$('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1048576)throw Error('任务说明超过 1 MiB');const next=validateTask(JSON.parse(await file.text()));task=next;selected=0;history=[];persist();render();notice('任务已导入，尚未执行。');}catch(error){notice('导入失败，现有草稿保留：'+error.message);}e.target.value='';};
if(D.mode==='author'){task=cleanupTask(makeTask('audio'));try{const saved=localStorage.getItem('voice-tools.task.v1');if(saved)task=validateTask(JSON.parse(saved));}catch(error){notice('无法恢复草稿：'+error.message+'。当前使用新任务，原存档未被覆盖。');}}
render();
})();
