const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../../docs/sip-studio/core.js');
const fixture=()=>{const env=C.defaultEnv(),item=C.makeCase(env.id);return {env,item,scenario:C.compile(item,env)};};
function rejectScenario(change,pattern){const {scenario}=fixture();change(scenario);assert.match(C.validateScenario(scenario).errors.join(';'),pattern);assert.throws(()=>C.importScenario(scenario));}
test('default scenario compiles exact CLI fields and accounts for trailing DTMF gap',()=>{const {scenario}=fixture();assert.deepEqual(C.validateScenario(scenario),{errors:[],warnings:[],knownDuration:5.52,unknownDuration:0});assert.equal(scenario.steps[1].action,'dtmf');assert.equal('id' in scenario.steps[1],false);assert.equal('label' in scenario.steps[1],false);});
test('Studio roundtrip preserves labels, tags, settings; renews identifiers',()=>{const {env,item}=fixture();item.steps[0].label='问候';const r=C.importDocument(C.exportDocument(item,env));assert.deepEqual(C.compile(r.item,r.env),C.compile(item,env));assert.equal(r.item.steps[0].label,'问候');assert.notEqual(r.item.steps[0].id,item.steps[0].id);});
test('CLI import fills runtime defaults without adding a hangup to imported behavior',()=>{const {item,env}=C.importScenario({schema_version:'1.0',target_uri:'sip:a@localhost',steps:[{action:'wait',seconds:1}]});assert.equal(item.steps.length,1);assert.equal(env.config.account.id_uri,'sip:voice-tools@127.0.0.1');assert.deepEqual(C.validateScenario(C.compile(item,env)).errors,[]);});
test('unknown action and plaintext credential are rejected, not silently erased',()=>{rejectScenario(s=>s.steps[0]={action:'exec',command:'x'},/action/);rejectScenario(s=>s.account.auth={username:'x',password:'bad',password_env:'PW'},/password/);});
test('unknown nested and top-level fields fail closed',()=>{rejectScenario(s=>s.branch=true,/未知字段/);rejectScenario(s=>s.steps[1].label='leak',/未知字段/);rejectScenario(s=>s.network.tcp=true,/未知字段/);});
test('invalid digits, methods, float timings and boundaries are rejected',()=>{for(const v of ['','a','123Z','1'.repeat(129)])rejectScenario(s=>s.steps[1].digits=v,/按键/);for(const v of [true,39,2001,160.5,NaN])rejectScenario(s=>s.steps[1].duration_ms=v,/持续时间/);rejectScenario(s=>s.steps[1].method='inband',/按键方式/);});
test('wait rejects nonfinite, boolean, and out of bounds',()=>{for(const v of [-1,901,true,Infinity,'1'])rejectScenario(s=>s.steps[0].seconds=v,/等待时间/);});
test('UDP URI validation rejects injection, TLS, invalid port and display name',()=>{for(const v of ['sips:a@b','sip:a@b;transport=tcp','sip:a@b:65536','sip:a@b\r\nX: y','Bob <sip:a@b>'])rejectScenario(s=>s.target_uri=v,/URI/);});
test('network parity, IPv4 and auth environment variable name are checked',()=>{rejectScenario(s=>s.network.rtp_port=4001,/偶数/);rejectScenario(s=>s.network.bind_address='999.0.0.1',/IPv4/);rejectScenario(s=>s.account.auth={username:'u',password_env:'a-b'},/环境变量名/);});
test('hangup only last, action counts and total duration enforced',()=>{rejectScenario(s=>s.steps.unshift({action:'hangup'}),/最后/);rejectScenario(s=>s.steps=[],/1–256/);rejectScenario(s=>s.steps=Array(257).fill({action:'wait',seconds:0}),/1–256/);rejectScenario(s=>s.max_call_s=5,/时长/);});
test('moving a step cannot cross the final hangup; input remains immutable',()=>{const {item}=fixture(),before=C.clone(item.steps),id=item.steps[0].id;const moved=C.moveStep(item.steps,id,99);assert.equal(moved.at(-1).action,'hangup');assert.equal(moved.at(-2).id,id);assert.deepEqual(item.steps,before);assert.deepEqual(C.moveStep(item.steps,item.steps.at(-1).id,0),before);});
test('missing media duration is unknown, never presented as zero-duration verified media',()=>{const {scenario}=fixture();scenario.steps[0]={action:'play',file:'assets/a.wav'};const v=C.validateScenario(scenario);assert.equal(v.unknownDuration,1);assert.equal(v.knownDuration,3.52);assert.equal(v.warnings.length,2);});
test('asset duration participates in budget but always retains CLI verification warning',()=>{const {scenario}=fixture();scenario.steps[0]={action:'play',file:'a.wav'};scenario.max_call_s=5;const v=C.validateScenario(scenario,[{kind:'wav',path:'a.wav',duration:2}]);assert.match(v.errors.join(),/时长/);assert.match(v.warnings.join(),/CLI/);});
test('Studio document rejects hidden secret fields and unsupported document version',()=>{const {item,env}=fixture(),doc=C.exportDocument(item,env);doc.steps[0].password='bad';assert.throws(()=>C.importDocument(doc),/未知/);delete doc.steps[0].password;doc.studio_version='2';assert.throws(()=>C.importDocument(doc),/版本/);});
function wav({rate=8000,channels=1,bits=16,seconds=.1}={}){const size=rate*channels*bits/8*seconds,b=Buffer.alloc(44+size);b.write('RIFF');b.writeUInt32LE(36+size,4);b.write('WAVE',8);b.write('fmt ',12);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(channels,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*channels*bits/8,28);b.writeUInt16LE(channels*bits/8,32);b.writeUInt16LE(bits,34);b.write('data',36);b.writeUInt32LE(size,40);for(let i=44;i<b.length-1;i+=2)b.writeInt16LE(Math.round(3000*Math.sin(i*.1)),i);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);}
test('WAV checks real RIFF PCM format and derives amplitude from actual samples',()=>{const r=C.wavInfo(wav());assert.equal(r.duration,.1);assert.equal(r.peaks.length,96);assert(r.peaks.every(p=>p>0&&p<.1));});
test('WAV rejects stereo, wrong sample rate, wrong bit depth, truncation and zero duration',()=>{for(const opts of [{channels:2},{rate:16000},{bits:8},{seconds:0}])assert.throws(()=>C.wavInfo(wav(opts)));assert.throws(()=>C.wavInfo(wav().slice(0,80)),/完整/);});
const media=()=>({schema_version:'1.0',audio:'audio.wav',audio_sha256:'a'.repeat(64),duration_s:1,dtmf:[{at_s:.1,digit:'1',duration_ms:160,end_observed:true}],source:{},warnings:[]});
test('media manifests validate event boundaries, never claim to have checked audio hash bytes',()=>{assert.equal(C.mediaInfo(media()).eventCount,1);const m=media();m.dtmf.push({at_s:.2,digit:'2',duration_ms:160});assert.throws(()=>C.mediaInfo(m),/重叠/);});
test('media rejects unsupported versions, malformed hash and oversized events',()=>{const m=media();m.schema_version='9';assert.throws(()=>C.mediaInfo(m));m.schema_version='1.0';m.audio_sha256='bad';assert.throws(()=>C.mediaInfo(m),/SHA256/);m.audio_sha256='a'.repeat(64);m.dtmf[0].duration_ms=1000;assert.throws(()=>C.mediaInfo(m),/超出/);});
test('explicit null never inherits defaults; non-string action cannot coerce into a known name',()=>{for(const k of ['account','network','codec','connect_timeout_s','max_call_s','record_early'])rejectScenario(s=>s[k]=null,/./);rejectScenario(s=>s.account.auth=null,/auth/);rejectScenario(s=>s.steps[0].action=['wait'],/action/);rejectScenario(s=>s.steps[1].gap_ms=null,/间隔/);});
test('latest main media contract checks boolean end_observed and floating point boundary tolerance',()=>{const m=media();m.dtmf[0].end_observed=1;assert.throws(()=>C.mediaInfo(m),/布尔/);m.dtmf=[{at_s:.1,digit:'1',duration_ms:200},{at_s:.3,digit:'2',duration_ms:200}];assert.equal(C.mediaInfo(m).eventCount,2);});
test('Studio environment cannot hide a second steps array or runtime version',()=>{const {item,env}=fixture(),doc=C.exportDocument(item,env);doc.environment.config.steps=[];assert.throws(()=>C.importDocument(doc),/未知字段/);});
